version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3307:3306'
    expose:
      - '3007'

  app:
    container_name: api-rest
    restart: always
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
